name: Check Semver
permissions: {}
on:
  workflow_dispatch: {}
jobs:
  check-semver:
    name: Check semver
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@5b298c9520f7096a4683c0bd981a7ac5a7e249ae
