name: Check Pull Requests
permissions: {}
on:
  workflow_dispatch: {}
jobs:
  check-title:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Check PR title
      if: github.event_name == 'pull_request_target'
      uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50
      id: check_pr_title
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
      if: always() && (steps.check_pr_title.outputs.error_message != null)
      with:
        header: pr-title-lint-error
        message: 'Thank you for opening this pull request!


          We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)
          and it looks like your proposed title needs to be adjusted.


          Details:


          > ${{ steps.check_pr_title.outputs.error_message }}

          '
    - if: ${{ steps.check_pr_title.outputs.error_message == null }}
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
      with:
        header: pr-title-lint-error
        delete: true
  check-breaking-change-label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
    - name: Check breaking change label
      id: check_breaking_change
      run: "pattern='^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\\
        (\\w+\\))?!:'\n# Check if pattern matches\nif echo \"${PR_TITLE}\" | grep\
        \ -qE \"$pattern\"; then\n  echo \"breaking_change=true\" >> $GITHUB_OUTPUT\n\
        else\n  echo \"breaking_change=false\" >> $GITHUB_OUTPUT\nfi\n"
    - name: Add label
      if: steps.check_breaking_change.outputs.breaking_change == 'true'
      uses: actions/github-script@v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "github.rest.issues.addLabels({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  labels: ['Type:\
          \ Breaking Change']\n})\n"
  do-not-merge:
    if: ${{ contains(github.event.*.labels.*.name, 'do not merge') }}
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
    - name: Check for label
      run: 'echo "Pull request is labeled as ''do not merge''"

        echo "This workflow fails so that the pull request cannot be merged"

        exit 1

        '
